### ISSUE TITLE
python error when running DeepTE.py

### ISSUE THREAD

**Issue by wyj-lzu** [LiLabAtVT/DeepTE#17]
Hi, 

When I use DeepTE.py, I meet an error like this :

Using TensorFlow backend.
start time is 1654048452.7466319
Step1: transfer fasta data to CNN input data
Step2: classify TEs
Step2: 1) domain information is exist
Traceback (most recent call last):
  File "/data/01/user152/software/DeepTE/DeepTE.py", line 274, in <module>
    main()
  File "/data/01/user152/software/DeepTE/DeepTE.py", line 243, in main
    pipeline_yes_m.classify_pipeline(model_dir, input_CNN_data_file, temp_store_opt_dir, sp_type,te_domain_pattern_dic,te_fam,prop_thr)
  File "/data/01/user152/software/DeepTE/scripts/DeepTE_pipeline_yes_modification.py", line 540, in classify_pipeline    predict_te(model_file_dic[model_name], model_name, x_all_test_list, y_all_test_nm_list,input_spe_type,te_domain_pattern_dic,y_all_test_nm_list,prop_thr)  File "/data/01/user152/software/DeepTE/scripts/DeepTE_pipeline_yes_modification.py", line 218, in predict_te
    model = load_model(model)
  File "/data/00/user/user152/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)  File "/data/00/user/user152/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 224, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

How to fix it?   And my command is DeepTE.py -d deepte_working_dir -o deepte_output_dir -i All-families.single.clstr.rename.fa -sp M -m_dir model_dir/Metazoans_model  -modify output_dir/opt_te_domain_pattern.txt

**Comment by wyj-lzu** [comment]
Hi,
 
I got the file yet.
[opt_te_domain_pattern.txt](https://github.com/LiLabAtVT/DeepTE/files/8932994/opt_te_domain_pattern.txt)

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey,

Sorry to reply late due to busy time recently. 
Would you share all of the input data to me that I can have a trying?

Best,
Haidong
