### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by helan-1997** [LiLabAtVT/DeepTE#21]
Hi,

When I use DeepTE.py, I meet an error like this :
`./DeepTE_domain.py -d ./working_dir -o ./output_dir -i result.fa -s ./supfile_dir --hmmscan hmmscan`
`./DeepTE.py -d ./working_dir -o ./output_dir -i result.fa  -m_dir /home/user/biosoft/DeepTE/ -sp M  -fam All -modify ./output_dir/opt_te_domain_pattern.txt`
then 
`Using TensorFlow backend.
start time is 1663231460.5417993
Step1: transfer fasta data to CNN input data
Step2: classify TEs
Step2: 1) domain information is exist
Traceback (most recent call last):
  File "./DeepTE.py", line 274, in <module>
    main()
  File "./DeepTE.py", line 243, in main
    pipeline_yes_m.classify_pipeline(model_dir, input_CNN_data_file, temp_store_opt_dir, sp_type,te_domain_pattern_dic,te_fam,prop_thr)
  File "/home/user/biosoft/DeepTE/scripts/DeepTE_pipeline_yes_modification.py", line 508, in classify_pipeline
    model_nm = mt.group(1)
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by yanhaidong1** [comment]
Hey,

Would you try to run './DeepTE.py -d ./working_dir -o ./output_dir -i result.fa -m_dir /home/user/biosoft/DeepTE/ -sp M -modify ./output_dir/opt_te_domain_pattern.txt' without specifying '-fam All' using the current version of DeepTE?
The current has updated to delete the '-fam All', and the default setting will directly classify all TEs. 

Best wishes,
Haidong

**Comment by Niohuruzh** [comment]
Hi,
I use the current DeepTE with the command `DeepTE.py -d deepwork/ -o deepTEout/ -i all.families.fa -sp F -m_dir /home/data`
but there is still the same problem:

> Using TensorFlow backend.
start time is 1675818480.4031475
Step1: transfer fasta data to CNN input data
Step2: classify TEs
Step2: 2) domain information is not exist
Traceback (most recent call last):
  File "/media/leigod/f83cb121-4d63-4d87-8adf-a7bdefb24a63/home/leigod/software/DeepTE/DeepTE.py", line 274, in <module>
    main()
  File "/media/leigod/f83cb121-4d63-4d87-8adf-a7bdefb24a63/home/leigod/software/DeepTE/DeepTE.py", line 249, in main
    pipeline_no_m.classify_pipeline(model_dir, input_CNN_data_file, temp_store_opt_dir, sp_type,te_fam,prop_thr)
  File "/media/leigod/f83cb121-4d63-4d87-8adf-a7bdefb24a63/home/leigod/software/DeepTE/scripts/DeepTE_pipeline_no_modification.py", line 307, in classify_pipeline
    model_nm = mt.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

What's wrong with my input data or environment?
Looking forward your reply!

**Comment by yanhaidong1** [comment]
Hey Niohuruzh,

Would you mind checking again if /home/data contain all the models you downloaded from the links attached in this github? looks like tool cannot find the model files. 

Best wishes,
Haidong

**Comment by Niohuruzh** [comment]
Hi Haidong,
Thanks for your quick reply.
My dataset `pwd` is 

> /media/data/Fungi_model.tar.gz

Should I decompress the file or just use ` -m_dir /media/data/Fungi_model.tar.gz` ？

**Comment by yanhaidong1** [comment]
Hey Niohuruzh,

Just decompress the file in your directory '/media/data/', under this directory, there are eight 'h5' format files if you decompress it correctly. Next use '-m_dir /media/data/'. I recommend you can also put all the h5 format files into a new directory like /media/F_models/ to run the tool based on '-m_dir /media/F_models/'

Best wishes,
Haidong

**Comment by Niohuruzh** [comment]
Hi Haidong,
 It works now. Thanks for your advice!
