### ISSUE TITLE
Error while running the example 

### ISSUE THREAD

**Issue by N-A-M** [LiLabAtVT/DeepTE#32]
Hi Haidong,

I'm executing the given example under the example_data directory using this command python3 DeepTE.py -d working_dir -o output_dir -i example_data/input_test.fasta -m O
but it gives a runtime error

Step2: 2) domain information is not exist
/home/mohamed.ne/.conda/envs/py36/lib/python3.6/site-packages/keras/utils/conv_utils.py:82: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.copy(kernel[slices])
Traceback (most recent call last):
  File "DeepTE.py", line 274, in <module>
    main()
  File "DeepTE.py", line 249, in main
    pipeline_no_m.classify_pipeline(model_dir, input_CNN_data_file, temp_store_opt_dir, sp_type,te_fam,prop_thr)
  File "/scratch/mohamed.ne/deepTE/DeepTE/scripts/DeepTE_pipeline_no_modification.py", line 339, in classify_pipeline
    predict_te(model_file_dic[model_name], model_name, x_all_test_list, y_all_test_nm_list,input_spe_type,y_all_test_nm_list,prop_thr)
  File "/scratch/mohamed.ne/deepTE/DeepTE/scripts/DeepTE_pipeline_no_modification.py", line 258, in predict_te
    store_results_dic[str(i)] = str(y_test_nm_list[i])  + '\t' + name_number_dic[model_nm][str(new_predicted_classes_list[i])]
KeyError: '1'

would you help!
Neveen

**Comment by N-A-M** [comment]
I found out the issue, it just needed a different numpy version (1.16.0) and a different theano : thanks for providing package version info
