### ISSUE TITLE
ImportError: cannot import name 'abs'

### ISSUE THREAD

**Issue by kuangzhuoran** [LiLabAtVT/DeepTE#37]
Hi, I use conda to install required packages and after installaton, I met these errors:

$ ./DeepTE.py -h
Using TensorFlow backend.
Traceback (most recent call last):
  File "./DeepTE.py", line 17, in <module>
    from scripts import DeepTE_pipeline_no_modification as pipeline_no_m
  File "/beegfs/home/kuangzhuoran/software/DeepTE/scripts/DeepTE_pipeline_no_modification.py", line 14, in <module>
    from keras.models import load_model
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 26, in <module>
    from tensorflow.python.keras import activations
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/activations/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 36, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 25, in <module>
    from tensorflow.python.keras import backend
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'
(DeepTE)

**Comment by songliVT** [comment]
this looks like a typical deoendency issue. I think a reinstall with a fresh conda environment could potentially solve this issue.

Song

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Zhuoran Kuang ***@***.***>
Sent: Tuesday, December 24, 2024 5:21:25 PM
To: LiLabAtVT/DeepTE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LiLabAtVT/DeepTE] ImportError: cannot import name 'abs' (Issue #37)


Hi, I use conda to install required packages and after installaton, I met these errors:

$ ./DeepTE.py -h
Using TensorFlow backend.
Traceback (most recent call last):
File "./DeepTE.py", line 17, in
from scripts import DeepTE_pipeline_no_modification as pipeline_no_m
File "/beegfs/home/kuangzhuoran/software/DeepTE/scripts/DeepTE_pipeline_no_modification.py", line 14, in
from keras.models import load_model
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/init.py", line 3, in
from . import utils
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/utils/init.py", line 6, in
from . import conv_utils
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in
from .. import backend as K
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/backend/init.py", line 89, in
from .tensorflow_backend import *
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in
import tensorflow as tf
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/init.py", line 28, in
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/init.py", line 83, in
from tensorflow.python import keras
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/init.py", line 26, in
from tensorflow.python.keras import activations
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/activations/init.py", line 22, in
from tensorflow.python.keras._impl.keras.activations import elu
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/init.py", line 21, in
from tensorflow.python.keras._impl.keras import activations
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 23, in
from tensorflow.python.keras._impl.keras import backend as K
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 36, in
from tensorflow.python.layers import base as tf_base_layers
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 25, in
from tensorflow.python.keras import backend
File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/keras/backend/init.py", line 22, in
from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'
(DeepTE)

―

**Comment by kuangzhuoran** [comment]
Thanks ! I reinstall with a new conda environment...
Well I use mamba instead of conda:
mamba create -n DeepTE python=3.6
conda activate  DeepTE
mamba install tensorflow-gpu=1.14.0
mamba install biopython
mamba install keras=2.2.4
mamba install numpy=1.16.0
pip install sklearn


And I also met errors:
Using TensorFlow backend.
Traceback (most recent call last):
  File "./DeepTE.py", line 17, in <module>
    from scripts import DeepTE_pipeline_no_modification as pipeline_no_m
  File "/beegfs/home/kuangzhuoran/software/DeepTE/scripts/DeepTE_pipeline_no_modification.py", line 14, in <module>
    from keras.models import load_model
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 54, in <module>
    from tensorflow.python.platform import app
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 23, in <module>
    from absl.app import run as _run
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/absl/app.py", line 37, in <module>
    from absl import flags
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/DeepTE/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
(DeepTE)

**Comment by kuangzhuoran** [comment]
Well, it also looks like a deoendency issue

**Comment by kuangzhuoran** [comment]
It solved. I used micromamba to create a new environment.
